name: attend_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  http_parser: ^3.1.4
  dio: ^3.0.9
  progress_dialog: ^1.2.4
  # flutter_video_compress: ^0.3.7+8
  flutter_custom_clippers: ^1.1.0
  cached_network_image: ^2.0.0
  rflutter_alert: ^1.0.3
  shared_preferences: ^0.5.6+3
  # shared_preferences: ^0.5.12+4
  #geo package related
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1
  camera: ^0.5.7+4
  image_picker: ^0.6.7+4
  path_provider: ^1.6.5
  path: ^1.6.4
  # Local Notification =======================
  # flutter_local_notifications: ^1.4.4+2
  # rxdart: ^0.24.1
  # meta: '>=1.1.0 <2.0.0'
  # redux: ^4.0.0
  # redux_persist: ^0.8.3
  # ==========================================
  # android_multiple_identifier: ^1.0.3
  device_info: ^0.4.2+8
  parse_server_sdk: ^1.0.27
  permission_handler: ^5.0.0+hotfix.8
  intl: ^0.16.1
  ntp: ^1.0.7
  # firebase cloud messaging
  # firebase_messaging: ^6.0.16
  firebase_ml_vision: ^0.9.0
  # firebase_ml_vision: ^0.7.0
  firebase_core: ^0.4.5
  # firebase_core: ^0.5.0
  # firebase_core: ^0.5.1
  crypto: ^2.1.4
  #map plugin
  google_maps_flutter: ^0.5.31
  flutter_polyline_points: ^0.2.3
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.2.1
  scrollable_positioned_list: ^0.1.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/dika.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
